gitlab ci - execute reddit-deploy deploy to production, when pushing to master

diff --git a/src/post-py/.gitlab-ci.yml b/src/post-py/.gitlab-ci.yml
--- a/src/post-py/.gitlab-ci.yml
+++ b/src/post-py/.gitlab-ci.yml
@@ -6,6 +6,7 @@ stages:
   - review
   - release
   - cleanup
+  - trigger
 
 build:
   stage: build
@@ -76,6 +77,13 @@ stop_review:
       - branches
     kubernetes: active
   except:
+    - master
+
+trigger_prod:
+  stage: trigger
+  script:
+    - trigger_production
+  only:
     - master
 
 .auto_devops: &auto_devops |
@@ -197,6 +205,63 @@ stop_review:
     name="$CI_ENVIRONMENT_SLUG"
     helm delete "$name" --purge || true
   }
+
+  function pstatus {
+    PIPELINE=$1
+    curl -s -X GET -H "PRIVATE-TOKEN: ${CI_TRIGGER_USER_TOKEN}" ${PROJ_URL}/pipelines/$PIPELINE | jq -r '.status'
+  }
+
+  function trigger_production() {
+    set -e
+    apk update && apk add curl jq
+    HOST="gitlab-gitlab"
+    URL_PATH="/api/v4/projects"
+    PROJ_URL="http://${HOST}${URL_PATH}/${CI_REDDIT_DEPLOY_PROJECT_ID}"
+
+    echo "Triggering pipeline ..."
+
+    cmd="curl -s -X POST -F token=${CI_REDDIT_DEPLOY_TOKEN} -F ref=master ${PROJ_URL}/trigger/pipeline"
+    ID=$(${cmd} | jq -r '.id')
+
+    if [ "${ID}" == 'null' ]; then
+      echo "Triggering pipeline failed"
+      echo "Please verify your parameters by running the following command manually:"
+      echo "${cmd[@]}"
+      exit 1
+    fi
+
+    echo Pipeline id: ${ID}
+
+    echo "Waiting for pipeline to finish ..."
+
+    # see https://docs.gitlab.com/ee/ci/pipelines.html for states
+    until [[ \
+      $( pstatus ${ID} ) = 'failed' \
+      || $( pstatus ${ID} ) = 'warning' \
+      || $( pstatus ${ID} ) = 'manual' \
+      || $( pstatus ${ID} ) = 'canceled' \
+      || $( pstatus ${ID} ) = 'success' \
+      || $( pstatus ${ID} ) = 'skipped' \
+    ]]
+    do
+      echo -n '.'
+      sleep 5
+    done
+
+    echo
+    echo Done
+
+    if [[ $( pstatus ${ID} ) != 'success' ]]; then
+      echo "Pipeline failed. Deploy to production will not be triggered"
+      exit 1
+    fi
+
+    JOB_ID=$(curl -s --header "PRIVATE-TOKEN:${CI_TRIGGER_USER_TOKEN}" ${PROJ_URL}/pipelines/${ID}/jobs | jq ".[] | select (.stage==\"production\") | .id")
+    echo "JOB_ID: ${JOB_ID}"
+    curl -s --request POST --header "PRIVATE-TOKEN:${CI_TRIGGER_USER_TOKEN}" "${PROJ_URL}/jobs/${JOB_ID}/play"
+    echo "Deploy to production job started"
+  }
+
 
 before_script:
   - *auto_devops
